services:
  mysql:
    image: 'mysql:latest'
#    command: '--init-file create_tables.sql'
    environment:
      - 'MYSQL_DATABASE=librarydatabase'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '3306'
