services:
  mysql:
    image: 'mysql:latest'
#    command: '--init-file /app_data/create_tables.sql'
    environment:
      - 'MYSQL_DATABASE=LIBRARY_DATABASE'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
      - 'TZ=America/Chicago'
    ports:
      - '3306'
    volumes:
      - './:/app_data'
